### ISSUE TITLE
How to catch errors

### ISSUE THREAD

**Issue by vinicentus** [danrubel/rpi_i2c.dart#2]
So I am testing a device. Sometimes it works well for a while, but I (seemingly) randomly get this error: 
```
Unhandled exception:
I2CException: operation failed: -1, address: 65, error: 121
#0      RpiI2CDevice._throwIfNegative (package:rpi_i2c/rpi_i2c.dart:62:7)
#1      RpiI2CDevice.readByte (package:rpi_i2c/rpi_i2c.dart:44:33)
#2      ArduinoPwmConverter.write (package:specialarbete_dart/communication/i2c/pwm/pwm_over_i2c_in.dart:26:32)
#3      readSensor (package:specialarbete_dart/communication/i2c/pwm/pwm_test.dart:26:19)
<asynchronous suspension>
#4      main (package:specialarbete_dart/communication/i2c/pwm/pwm_test.dart:13:9)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

Now I want to make sure my main program doesn't stop running just because there was an error with the i2c communication. I have tried reading the i2c bus inside a try/catch statement but it stil throws and exits the main program.

How should I go about fixing this?

**Comment by vinicentus** [comment]
It seems like it catches the errors after all... Don't know what caused this but my application is working now so whatever...
